env:
  contexts:
    - name: "opensidscan"
      urls:
        - "https://masi.devrun.cloud"
      includePaths:
        - "https://masi.devrun.cloud.*"
jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 100
  - type: spider
    parameters:
      context: "opensidscan"
      maxDuration: 2
  - type: passiveScan-wait
  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk/reports
      reportTitle: "OpenSID ZAP Report"
      reportFile: "opensid-zap-report.html"
