env:
  contexts:
    - name: OpenSID
      urls:
        - https://masi.devrun.cloud

jobs:
  - type: spider
    parameters:
      context: OpenSID
      maxDuration: 10

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      policy: Default Policy
      maxDuration: 15

  - type: report
    parameters:
      template: traditional-html
      reportFile: opensid-timed-report-20250410-142610.html
      reportDir: /zap/wrk/reports
